//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public int NotId { get; set; }
        public int Sinav1 { get; set; }
        public int Sinav2 { get; set; }
        public int Performans { get; set; }
        public int Proje { get; set; }
    }
}
